version: '3'
services:
  minio:
    image: ${MINIO_IMAGE}
    ports:
     - "127.0.0.1:9100:9100"
     - "127.0.0.1:9101:9101"
    environment:
     - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
     - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    volumes:
     - ./minio:/data
    command: server /data --address ":9100" --console-address ":9101"

  snellerd:
    image: snellerinc/snellerd:latest
    ports:
     - "127.0.0.1:9180:9180"
    environment:
     - CACHEDIR=/var/cache/sneller
    env_file:
     - .env
    tmpfs:
     - /var/cache/sneller:size=${CACHESIZE}
    command: daemon -e 0.0.0.0:9180

networks:
  default:
    name: sneller-network
